type ItemTier = 1 | 2 | 3 | 4;

type ItemCategory = "weapon" | "vitality" | "spirit";

interface ItemStat {
  name: ItemStatName;
  amount: number;
  type?: "flat" | "percentage";
}

export interface Item {
  name: string;
  category: ItemCategory;
  tier: ItemTier;
  component?: string;
  stats: ItemStat[];
  passive?: {
    stats: ItemStat[];
    cooldown?: number;
    duration?: number;
    condition?: ItemConditionName;
  };
  active?: {
    stats: ItemStat[];
    cooldown: number;
    duration?: number;
    condition?: ItemConditionName;
  };
  additionalInfo?: string;
}

// List of all stat names, useful for typescript name hinting.
export type ItemStatName =
  | "alchemical_fire"
  | "ammo"
  | "ammo_scavenger"
  | "base_health"
  | "bleed_damage"
  | "bonus_ammo"
  | "bonus_health"
  | "bonus_spirit_damage"
  | "bonus_weapon_damage"
  | "bonus_heavy_melee_damage"
  | "boundless_spirit"
  | "bullet_armor"
  | "bullet_heal"
  | "bullet_lifesteal"
  | "bullet_shield_health"
  | "bullet_velocity"
  | "bullet_resist"
  | "bullet_resist_shredder"
  | "bullet_resist_vs_npcs"
  | "cold_front"
  | "colossus"
  | "combat_barrier"
  | "crippling_headshot"
  | "curse"
  | "dash_jump"
  | "debuff_reducer"
  | "debuff_remover"
  | "decay"
  | "diviners_kevlar"
  | "duration_extender"
  | "divine_barrier"
  | "echo_shard"
  | "enchanters_barrier"
  | "enduring_speed"
  | "enduring_spirit"
  | "escalating_exposure"
  | "ethereal_shift"
  | "extra_charge"
  | "extra_health"
  | "extra_regen"
  | "extra_spririt"
  | "extra_stamina"
  | "fire_rate"
  | "fire_rate_slow"
  | "fortitude"
  | "frenzy"
  | "glass_cannon"
  | "healbane"
  | "healing"
  | "healing_booster"
  | "healing_reduction"
  | "health_nova"
  | "health_regen"
  | "healing_rite"
  | "heavy_melee_distance"
  | "heroic_aura"
  | "improved_bullet_armor"
  | "improved_burst"
  | "improved_cooldown"
  | "improved_reach"
  | "improved_spirit"
  | "improved_spirit_armor"
  | "infuser"
  | "inhibitor"
  | "intensifying_magazine"
  | "knockdown"
  | "leech"
  | "lifestrike"
  | "lucky_shot"
  | "max_weapon_damage"
  | "magic_carpet"
  | "majestic_leap"
  | "melee_lifesteal"
  | "metal_skin"
  | "minion_fire_rate"
  | "movement_slow"
  | "movement_speed"
  | "mystic_burst"
  | "mystic_reach"
  | "mystic_reverb"
  | "mystic_slow"
  | "mystic_vulnerability"
  | "phantom_strike"
  | "point_blank"
  | "pristine_emblem"
  | "quicksilver_reload"
  | "rapid_recharge"
  | "reactive_barrier"
  | "reduce_enemy_bullet_resist"
  | "reduce_enemy_fire_rate"
  | "refresher"
  | "reload_time"
  | "rescue_beam"
  | "restorative_locket"
  | "return_fire"
  | "ricochet"
  | "shadow_weave"
  | "sharpshooter"
  | "shock_damage"
  | "shock_change"
  | "silence_glyph"
  | "silencer"
  | "siphon_bullets"
  | "slide_distance"
  | "slowing_hex"
  | "soul_rebirth"
  | "spirit_amp"
  | "spirit_armor"
  | "spirit_dps"
  | "spirit_lifesteal"
  | "spirit_power"
  | "spirit_resist"
  | "spirit_shield_health"
  | "spirit_strike"
  | "sprint_speed"
  | "spiritual_overflow"
  | "sprint_boots"
  | "stamina"
  | "superior_cooldown"
  | "superior_duration"
  | "superior_stamina"
  | "suppressor"
  | "surge_of_power"
  | "temporary_ammo"
  | "tesla_bullets"
  | "titanic_magazine"
  | "torment_pulse"
  | "toxic_bullets"
  | "unstoppable"
  | "vampiric_burst"
  | "veil_walker"
  | "warp_stone"
  | "weapon_damage"
  | "weapon_damage_vs_npcs"
  | "weapon_falloff_range"
  | "weapon_zoom"
  | "withering_whip";

// List of all stat conditions, useful for typescript name hinting.
export type ItemConditionName =
  | "active_reload"
  | "close_range_15m"
  | "continuous_fire"
  | "damage_over_time"
  | "enemy_health_above_50%"
  | "headshot"
  | "health_above_60%"
  | "heavy_melee"
  | "hit_hero"
  | "kinetic_dash"
  | "long_range_15m"
  | "minions_nearby_20m"
  | "next_bullet"
  | "sustain_damage_from_enemies"
  | "stacking"
  | "teleport_11m"
  | "radius";
